"""
Sector-wise Stock Mapping
Maps each NIFTY sector index to its constituent stocks
"""

# Banking Sector Stocks
BANK_NIFTY_STOCKS = [
    "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "KOTAKBANK.NS", "AXISBANK.NS",
    "INDUSINDBK.NS", "BANKBARODA.NS", "PNB.NS", "FEDERALBNK.NS", "IDFCFIRSTB.NS",
    "BANDHANBNK.NS", "AUBANK.NS"
]

# Nifty IT Stocks
NIFTY_IT_STOCKS = [
    "TCS.NS", "INFY.NS", "HCLTECH.NS", "WIPRO.NS", "TECHM.NS",
    "LTIM.NS", "MPHASIS.NS", "COFORGE.NS", "PERSISTENT.NS", "LTTS.NS"
]

# Nifty Pharma Stocks
NIFTY_PHARMA_STOCKS = [
    "SUNPHARMA.NS", "DRREDDY.NS", "CIPLA.NS", "DIVISLAB.NS", "APOLLOHOSP.NS",
    "TORNTPHARM.NS", "ZYDUSLIFE.NS", "BIOCON.NS", "LUPIN.NS", "AUROPHARMA.NS",
    "ALKEM.NS", "GLAND.NS", "IPCALAB.NS", "LAURUSLABS.NS", "NATCOPHARM.NS"
]

# Nifty FMCG Stocks
NIFTY_FMCG_STOCKS = [
    "HINDUNILVR.NS", "ITC.NS", "NESTLEIND.NS", "BRITANNIA.NS", "DABUR.NS",
    "MARICO.NS", "COLPAL.NS", "GODREJCP.NS", "TATACONSUM.NS", "VBL.NS",
    "UBL.NS", "MCDOWELL-N.NS", "PGHH.NS", "EMAMILTD.NS"
]

# Nifty Auto Stocks
NIFTY_AUTO_STOCKS = [
    "MARUTI.NS", "TATAMOTORS.NS", "M&M.NS", "BAJAJ-AUTO.NS", "HEROMOTOCO.NS",
    "EICHERMOT.NS", "ASHOKLEY.NS", "TVSMOTOR.NS", "MOTHERSON.NS", "BHARATFORG.NS",
    "BALKRISIND.NS", "MRF.NS", "BOSCHLTD.NS", "EXIDEIND.NS"
]

# Nifty Metal Stocks
NIFTY_METAL_STOCKS = [
    "TATASTEEL.NS", "JSWSTEEL.NS", "HINDALCO.NS", "VEDL.NS", "JINDALSTEL.NS",
    "NMDC.NS", "SAIL.NS", "NATIONALUM.NS", "COALINDIA.NS", "APLAPOLLO.NS",
    "RATNAMANI.NS", "WELCORP.NS"
]

# Nifty Realty Stocks
NIFTY_REALTY_STOCKS = [
    "DLF.NS", "GODREJPROP.NS", "OBEROIRLTY.NS", "PHOENIXLTD.NS", "PRESTIGE.NS",
    "BRIGADE.NS", "SOBHA.NS", "SUNTECK.NS", "LODHA.NS"
]

# Nifty Energy Stocks
NIFTY_ENERGY_STOCKS = [
    "RELIANCE.NS", "ONGC.NS", "NTPC.NS", "POWERGRID.NS", "BPCL.NS",
    "IOC.NS", "GAIL.NS", "ADANIGREEN.NS", "TATAPOWER.NS", "ADANIENSOL.NS",
    "PETRONET.NS", "HINDPETRO.NS"
]

# Nifty Finance Stocks
NIFTY_FINANCE_STOCKS = [
    "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "KOTAKBANK.NS", "AXISBANK.NS",
    "BAJFINANCE.NS", "BAJAJFINSV.NS", "HDFCLIFE.NS", "SBILIFE.NS", "ICICIPRULI.NS",
    "ICICIGI.NS", "HDFCAMC.NS", "SBICARD.NS", "CHOLAFIN.NS", "MUTHOOTFIN.NS",
    "PFC.NS", "RECLTD.NS", "SHRIRAMFIN.NS"
]

# Nifty PSU Bank Stocks
NIFTY_PSU_BANK_STOCKS = [
    "SBIN.NS", "BANKBARODA.NS", "PNB.NS", "CANBK.NS", "UNIONBANK.NS",
    "IOB.NS", "INDIANB.NS", "CENTRALBK.NS", "BANKINDIA.NS", "MAHABANK.NS",
    "PSB.NS", "UCOBANK.NS"
]

# Nifty Private Bank Stocks
NIFTY_PVT_BANK_STOCKS = [
    "HDFCBANK.NS", "ICICIBANK.NS", "KOTAKBANK.NS", "AXISBANK.NS", "INDUSINDBK.NS",
    "FEDERALBNK.NS", "IDFCFIRSTB.NS", "BANDHANBNK.NS", "RBLBANK.NS", "YESBANK.NS"
]

# Nifty Media Stocks
NIFTY_MEDIA_STOCKS = [
    "ZEEL.NS", "PVRINOX.NS", "SUNTV.NS", "TV18BRDCST.NS", "NETWORK18.NS",
    "DISHTV.NS", "HATHWAY.NS", "NAZARA.NS", "SAREGAMA.NS"
]

# Nifty Infra Stocks
NIFTY_INFRA_STOCKS = [
    "LT.NS", "ADANIPORTS.NS", "ULTRACEMCO.NS", "GRASIM.NS", "SHREECEM.NS",
    "AMBUJACEM.NS", "ACC.NS", "DALBHARAT.NS", "RAMCOCEM.NS", "JKCEMENT.NS",
    "IRCON.NS", "NBCC.NS"
]

# Nifty Midcap Stocks (Top 20)
NIFTY_MIDCAP_STOCKS = [
    "POLYCAB.NS", "TRENT.NS", "PERSISTENT.NS", "MPHASIS.NS", "COFORGE.NS",
    "VOLTAS.NS", "ASTRAL.NS", "BHARATFORG.NS", "CUMMINSIND.NS", "SYNGENE.NS",
    "PAGEIND.NS", "AFFLE.NS", "ESCORTS.NS", "CROMPTON.NS", "SUPREMEIND.NS",
    "FLUOROCHEM.NS", "KPITTECH.NS", "SONACOMS.NS", "HAPPSTMNDS.NS", "ANGELONE.NS"
]

# Mapping sector index to stocks
SECTOR_STOCKS_MAP = {
    "Bank Nifty": BANK_NIFTY_STOCKS,
    "Nifty IT": NIFTY_IT_STOCKS,
    "Nifty Pharma": NIFTY_PHARMA_STOCKS,
    "Nifty FMCG": NIFTY_FMCG_STOCKS,
    "Nifty Auto": NIFTY_AUTO_STOCKS,
    "Nifty Metal": NIFTY_METAL_STOCKS,
    "Nifty Realty": NIFTY_REALTY_STOCKS,
    "Nifty Energy": NIFTY_ENERGY_STOCKS,
    "Nifty Finance": NIFTY_FINANCE_STOCKS,
    "Nifty PSU Bank": NIFTY_PSU_BANK_STOCKS,
    "Nifty Pvt Bank": NIFTY_PVT_BANK_STOCKS,
    "Nifty Media": NIFTY_MEDIA_STOCKS,
    "Nifty Infra": NIFTY_INFRA_STOCKS,
    "Nifty Midcap 100": NIFTY_MIDCAP_STOCKS,
}

# All sector stocks combined
ALL_SECTOR_STOCKS = list(set(
    BANK_NIFTY_STOCKS + NIFTY_IT_STOCKS + NIFTY_PHARMA_STOCKS + 
    NIFTY_FMCG_STOCKS + NIFTY_AUTO_STOCKS + NIFTY_METAL_STOCKS +
    NIFTY_REALTY_STOCKS + NIFTY_ENERGY_STOCKS + NIFTY_FINANCE_STOCKS +
    NIFTY_PSU_BANK_STOCKS + NIFTY_PVT_BANK_STOCKS + NIFTY_MEDIA_STOCKS +
    NIFTY_INFRA_STOCKS + NIFTY_MIDCAP_STOCKS
))
